# Generated by Django 3.2.8 on 2022-04-06 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name_all', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name_all', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('chip', models.CharField(default='', max_length=100)),
                ('thread', models.CharField(default='', max_length=100)),
                ('speed', models.CharField(default='', max_length=100)),
                ('foot_position_cpu', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('display_chip', models.CharField(default='', max_length=100)),
                ('Memory', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('capacity_TB', models.FloatField(default='0.0', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('Rotating_speed', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('foot_position_MB', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('Memory_Specifications', models.CharField(default='', max_length=100)),
                ('capacity_GB', models.IntegerField(default='')),
                ('type', models.CharField(default='', max_length=100)),
                ('clock_rate', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('Watts', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ssd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
                ('capacity_TB', models.FloatField(default='0.0', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('read_speed_mbs', models.IntegerField(default='')),
                ('write_speed_mbs', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='total_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('total', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='帳號名稱')),
            ],
        ),
    ]
