# Generated by Django 3.2.8 on 2022-04-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdb',
            old_name='name_all',
            new_name='name',
        ),
    ]
