# Generated by Django 3.2.8 on 2022-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0002_auto_20220320_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_db',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
