# Generated by Django 3.2.8 on 2022-05-23 12:02

from django.db import migrations, models
import hitcount.models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0002_rename_name_all_cartdb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('published_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
    ]
