# Generated by Django 3.2.8 on 2021-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0002_location_asdress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='asdress',
        ),
    ]
