# Generated by Django 3.2.8 on 2022-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0003_total_db_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_db',
            name='total',
            field=models.IntegerField(default='0'),
        ),
    ]
