# Generated by Django 3.2.8 on 2021-12-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0006_auto_20211211_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=500)),
            ],
        ),
    ]
