# Generated by Django 3.2.8 on 2021-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0007_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='aartist',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charts',
            name='arstist',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
