# Generated by Django 3.2.8 on 2021-12-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0008_auto_20211211_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=500)),
                ('commodity', models.CharField(max_length=3000)),
                ('url_list', models.CharField(max_length=3000)),
                ('pc_images', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='charts',
        ),
    ]
