# Generated by Django 3.2.8 on 2021-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0013_auto_20211228_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='Vendor',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='display',
            name='Vendor',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='Vendor',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
