# Generated by Django 3.2.8 on 2022-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0017_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
