# Generated by Django 3.2.8 on 2022-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0018_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', '動作片'), ('romance', '愛情片'), ('drama', '劇情片')], default='', max_length=20),
        ),
    ]
