# Generated by Django 3.2.8 on 2022-02-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0020_cpu_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='name',
            new_name='name1',
        ),
        migrations.AlterField(
            model_name='cpu',
            name='genre',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], default='', max_length=20),
        ),
    ]
