# Generated by Django 3.2.8 on 2022-02-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0023_rename_name_all_name1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='genre',
        ),
    ]
