# Generated by Django 3.2.8 on 2022-02-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0024_auto_20220219_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='name1',
            new_name='name_all',
        ),
    ]
