# Generated by Django 3.2.8 on 2022-03-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0026_auto_20220225_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='chassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='hdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='MB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='')),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
    ]
