# Generated by Django 3.2.8 on 2022-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0030_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='test',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
