# Generated by Django 3.2.8 on 2022-03-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0032_remove_cpu_test'),
    ]

    operations = [
        
        
        migrations.AddField(
            model_name='cpu',
            name='speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cpu',
            name='thread',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='display',
            name='Memory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='display',
            name='display_chip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hdd',
            name='Rotating_speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hdd',
            name='capacity_TB',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hdd',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        
        migrations.AddField(
            model_name='memory',
            name='Memory_Specifications',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memory',
            name='capacity_GB',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='memory',
            name='clock_rate',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='memory',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='power',
            name='Watts',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ssd',
            name='capacity_TB',
            field=models.FloatField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ssd',
            name='read_speed_mbs',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ssd',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ssd',
            name='write_speed_mbs',
            field=models.IntegerField(default=''),
        ),
    ]
