# Generated by Django 3.2.8 on 2022-03-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0035_auto_20220315_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='chip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cpu',
            name='foot_position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cpu',
            name='speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cpu',
            name='thread',
            field=models.CharField(default='', max_length=100),
        ),
    ]
