# Generated by Django 3.2.8 on 2022-03-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0037_auto_20220316_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='Rotating_speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hdd',
            name='capacity_TB',
            field=models.FloatField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='hdd',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
