# Generated by Django 3.2.8 on 2022-03-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0040_rename_foot_position_mb_foot_position_mb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='foot_position',
            new_name='foot_position_cpu',
        ),
    ]
