# Generated by Django 3.2.8 on 2022-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='db',
            name='total_db',
        ),
    ]
