# Generated by Django 3.2.8 on 2021-12-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0005_auto_20211118_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
