# Generated by Django 3.2.8 on 2021-12-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0011_aaa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aaa',
            new_name='cpu',
        ),
    ]
