# Generated by Django 3.2.8 on 2021-12-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0012_rename_aaa_cpu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='', max_length=500)),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='cpu',
            name='Vendor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cpu',
            name='pc_images',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='cpu',
            name='url_list',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='display',
            name='Vendor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='commodity',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='display',
            name='commodity',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='display',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='display',
            name='pc_images',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='display',
            name='price',
            field=models.IntegerField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='display',
            name='url_list',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
