# Generated by Django 3.2.8 on 2021-12-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0015_auto_20211228_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='vendor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='display',
            name='vendor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ssd',
            name='vendor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
