# Generated by Django 3.2.8 on 2022-02-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0016_auto_20211228_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default='', max_length=500)),
                ('commodity', models.CharField(default='', max_length=3000)),
                ('url_list', models.CharField(default='', max_length=3000)),
                ('pc_images', models.CharField(default='', max_length=3000)),
            ],
        ),
    ]
