# Generated by Django 3.2.8 on 2022-02-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0021_auto_20220219_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='name1',
            new_name='name',
        ),
    ]
