# Generated by Django 3.2.8 on 2022-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0025_rename_name1_all_name_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='display',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='price',
            field=models.IntegerField(default=''),
        ),
    ]
