# Generated by Django 3.2.8 on 2022-03-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0027_chassis_hdd_mb_memory_power'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chassis',
        ),
        migrations.DeleteModel(
            name='hdd',
        ),
        migrations.DeleteModel(
            name='MB',
        ),
        migrations.DeleteModel(
            name='Memory',
        ),
        migrations.DeleteModel(
            name='Power',
        ),
    ]
