# Generated by Django 3.2.8 on 2022-03-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0034_auto_20220315_2047'),
    ]

    operations = [
        
        
        migrations.RemoveField(
            model_name='cpu',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='thread',
        ),
    ]
