# Generated by Django 3.2.8 on 2022-03-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func3api', '0036_auto_20220315_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdd',
            name='Rotating_speed',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='capacity_TB',
        ),
        migrations.RemoveField(
            model_name='hdd',
            name='size',
        ),
    ]
